---
name: Nightly build CI

on:
  push:
    paths:
      - .github/workflows/nightly.yml
      - Dockerfile.client.production
      - Dockerfile.server.production
      - apps/client/**
      - apps/server/**
      - yarn.lock
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # … checkout, setup steps …
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client nightly
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.client.production
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.docker-meta.outputs.labels }}
          tags: |
            ghcr.io/${{ github.repository }}/client-nightly
            ghcr.io/${{ github.repository }}/client-${{ github.sha }}

      - name: Build and push server nightly
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.server.production
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.docker-meta.outputs.labels }}
          tags: |
            ghcr.io/${{ github.repository }}/server-nightly
            ghcr.io/${{ github.repository }}/server-${{ github.sha }}
